version: '3.5'

services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    external_links:
      - coopcycle-web_nginx_1
    image: wordpress:latest
    ports:
      - '9000:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    volumes:
      - ./wp-content/plugins/coopcycle:/var/www/html/wp-content/plugins/coopcycle

volumes:
  dbdata:

networks:
  default:
    external:
      name: coopcycleweb_default
